global:
  scrape_interval: 15s

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
      - targets: ['10.0.2.30:9100']
      - targets: ['10.0.2.45:9100']
      - targets: ['10.0.3.230:9100']
      - targets: ['10.0.2.156:9100']
      - targets: ['10.0.2.50:9100']
      - targets: ['10.0.3.240:9100']
      - targets: ['10.0.2.20:9100']
      - targets: ['10.0.5.208:9100']

  - job_name: 'blackbox_exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
        - localhost:9115
        labels:
          group: 'production'

  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets:
        - localhost:3000

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
